### ISSUE TITLE
Only works on one menu

### ISSUE THREAD

**Issue by merissler** [merissler/jira-ticket-color-changer#1]
(not counting the individual ticket page)

`https://goodstech.atlassian.net/jira/your-work`

**Comment by JJSnader** [comment]
You can make it work on dashboards by adding `ticketLinkElements = ticketLinkElements.concat(Array.from(document.getElementsByClassName("issue-link")))` and `ticketTexts = ticketTexts.concat(Array.from(document.getElementsByClassName("issue-link")))`. I would make a PR but I either don't know what I'm doing or just am not allowed to make a PR.

**Comment by merissler** [comment]
Implemented 👍
